version: '3.7'

services:
  juiceshop:
    build: .
    user: root
    restart: always
    ports:
      - "3290:3000"
    environment:
      - NODE_ENV=shell
      - RAW_EVAL=1
      - AWS_ACCESS_KEY_ID = AKIA35OHX2DSDD3DOLY5
      - AWS_SECRET_ACCESS_KEY = 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
      - SLACK_API_KEY = HFE7FHIH/FEDFEYhfeouyGDKJEH743IOFUEOIU/ferFHD
    depends_on:
      - attacker
    networks:
        default:
        internal:

  attacker:
    image: ubuntu
    restart: always
    command: tail -F anything
    networks:
        default:
        internal:

networks:
    default:
    internal:
        internal: true
