server:
  port: 3000
application:
  domain: codemash.org
  name: 'Shelleys Store'
  logo: JuiceShop_Logo.png
  favicon: favicon_js.ico
  numberOfRandomFakeUsers: 1
  showChallengeSolvedNotifications: false
  showChallengeHints: false
  showVersionNumber: false
  theme: blue-lightblue # Options: bluegrey-lightgreen blue-lightblue deeppurple-amber indigo-pink pink-bluegrey purple-green deeporange-indigo
  gitHubRibbon: false
  twitterUrl: 'https://twitter.com/jkuemerle'
  facebookUrl: 'https://www.facebook.com/owasp.juiceshop'
  slackUrl: 'http://owaspslack.com'
  pressKitUrl: 'https://github.com/OWASP/owasp-swag/tree/master/projects/juice-shop'
  planetOverlayMap: orangemap2k.jpg
  planetName: Orangeuze
  recyclePage:
    topProductImage: fruit_press.jpg
    bottomProductImage: apple_pressings.jpg
  altcoinName: Baconcoin
  cookieConsent:
    backgroundColor: '#546e7a'
    textColor: '#ffffff'
    buttonColor: '#558b2f'
    buttonTextColor: '#ffffff'
    message: 'This website uses  cookies to ensure you get the best experience.'
    dismissText: 'Me want it!'
    linkText: 'But me wait!'
    linkUrl: 'https://www.youtube.com/watch?v=9PnbKL3wuH4'
  securityTxt:
    contact: 'mailto:donotreply@owasp-juice.shop'
    encryption: 'https://keybase.io/bkimminich/pgp_keys.asc?fingerprint=19c01cb7157e4645e9e2c863062a85a8cbfbdcda'
    acknowledgements: '/#/score-board'
  promotion:
    video: JuiceShopJingle.mp4
    subtitles: JuiceShopJingle.vtt
challenges:
    safetyOverride: false
    overwriteUrlForProductTamperingChallenge: 'https://owasp.slack.com'
products:
  -
    name: 'Hair Dye'
    price: 19.99
    description: 'Very fine dye. Speaking of which, has anyone ever seen Brian and Count Olaf in the same room?.'
    image: orange-hair.jpeg
    reviews: # Options 'author': admin, jim, bender, ciso, support, morty, mc.safesearch
      - { text: 'One of my favorites!', author: admin }
  -
    name: 'Sugar Bowl'
    description: 'Great for storing sugar. Or secrets.'
    price: 29.99
    urlForProductTamperingChallenge: 'https://www.owasp.org/index.php/O-Saft'
    image: sugarbowl.jpg
  -
    name: 'Red Herring'
    description: 'Very fresh dining.'
    price: 19.99
    image: redherring.jpg
    fileForRetrieveBlueprintChallenge: JuiceShop.stl # ...to blueprint file type
    reviews:
      - { text: 'I bought it, would buy again. 5/7', author: admin }
  -
    name: 'Hair Ribbons'
    description: 'Great for when you need to concentrate on inventing.'
    price: 10.99
    image: hairtie.jpg
    keywordsForPastebinDataLeakChallenge:
      - hueteroneel
      - eurogium edule
  -
    name: 'Spyglass'
    description: 'Visualize faraway depictions.'
    price: 14.99
    image: spyglass.jpg
  -
    name: 'The Incomplete Reference of Secret Organizations'
    description: 'Very fine descriptions.'
    price: 14.99
    image: Tihoso_cover.jpg
    reviews:
      - { text: 'Fry liked it too.', author: bender }
  -
    name: 'Grappling Hook'
    description: 'Very forked device.'
    price: 249.99
    useForChristmasSpecialChallenge: true
    image: hook.jpg
  -
    name: 'Verdant Flammable Device'
    description: 'Visible fog distributor.'
    price: 22.99
    image: GreenFlamers.png
  -
    name: 'Self-Sustaining Hot Air Mobile Home'
    description: 'Vehicle for departure.'
    price: 65499.99
    image: MobileHome.png
ctf:
  showFlagsInNotifications: false
  showCountryDetailsInNotifications: none # Options: none  name  flag  both
  countryMapping: ~
